services:
  - type: web
    name: jean-informatico-restaurante-frontend
    runtime: node
    repo: https://github.com/jeffersonm-dev/Jean-informatico-Restaurante-Frontend
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm run dev -- --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    autoDeploy: true
    
    envVars:
      - key: VITE_API_URL
        value: https://restaurante-api-uam4.onrender.com/api
      - key: VITE_APP_TITLE
        value: Jean Informático Restaurante
      - key: NODE_ENV
        value: development
      - key: PORT
        value: 5173